// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Xchq4sr4eVAstNfIeWpZCy18yyDdOf8',
    appId: '1:611101075233:web:9af5aee70ff6953442c060',
    messagingSenderId: '611101075233',
    projectId: 'quick-card-317d4',
    authDomain: 'quick-card-317d4.firebaseapp.com',
    storageBucket: 'quick-card-317d4.firebasestorage.app',
    measurementId: 'G-7FQ6JR13BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHr6wLIh6ZUv7mput4twf1bDMzBENSANg',
    appId: '1:611101075233:android:901e19e72d5f539c42c060',
    messagingSenderId: '611101075233',
    projectId: 'quick-card-317d4',
    storageBucket: 'quick-card-317d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9D8Z9Ddq8bBQ3xBiGSRiZtcwt7-7vEA0',
    appId: '1:611101075233:ios:f8edaf5efd69775942c060',
    messagingSenderId: '611101075233',
    projectId: 'quick-card-317d4',
    storageBucket: 'quick-card-317d4.firebasestorage.app',
    iosBundleId: 'com.quickcard.app.quickCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9D8Z9Ddq8bBQ3xBiGSRiZtcwt7-7vEA0',
    appId: '1:611101075233:ios:f8edaf5efd69775942c060',
    messagingSenderId: '611101075233',
    projectId: 'quick-card-317d4',
    storageBucket: 'quick-card-317d4.firebasestorage.app',
    iosBundleId: 'com.quickcard.app.quickCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Xchq4sr4eVAstNfIeWpZCy18yyDdOf8',
    appId: '1:611101075233:web:73df274b4240525d42c060',
    messagingSenderId: '611101075233',
    projectId: 'quick-card-317d4',
    authDomain: 'quick-card-317d4.firebaseapp.com',
    storageBucket: 'quick-card-317d4.firebasestorage.app',
    measurementId: 'G-EB68MHD8QJ',
  );
}
